
export const ISLOADING = 'ISLOADING';
//Grid Types

export const PRESS_ARROW_RIGHT = 'PRESS_ARROW_RIGHT';
export const INCREMENT_CELL_VALUE = 'INCREMENT_CELL_VALUE';
export const DECREMENT_CELL_VALUE = 'DECREMENT_CELL_VALUE';
export const PRESS_ARROW_LEFT = 'PRESS_ARROW_LEFT';
export const PRESS_ARROW_UP = 'PRESS_ARROW_UP';
export const PRESS_ARROW_DOWN = 'PRESS_ARROW_DOWN';
export const UPDATE_ACTIVE_CELL_ID = 'UPDATE_ACTIVE_CELL_ID';
export const PRESS_ARROW_SPACE = 'PRESS_ARROW_SPACE';
export const NUMPAD_SUBTRACT = 'NUMPAD_SUBTRACT';
export const NUMPAD_ADD = 'NUMPAD_ADD';

//Wheather Types 

export const SET_WEATHER_LIST = 'SET_WEATHER_LIST';
export const UPDATE_WEATHER_BY_CITY = 'UPDATE_WEATHER_BY_CITY';
export const ADD_WEATHER_BY_CITY = 'ADD_WEATHER_BY_CITY';
export const CREATE_WEATHER_LIST = 'CREATE_WEATHER_LIST';
export const WEATHER_ERROR_MESSAGE = 'WEATHER_ERROR_MESSAGE';
export const DELETE_CITY_BY_ID = 'DELETE_CITY_BY_ID';
export const UPDATE_WEATHER_BY_CITY_DETAILS = 'UPDATE_WEATHER_BY_CITY_DETAILS';